# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='thresholdSamples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R', models.FloatField()),
                ('m', models.FloatField()),
                ('mse', models.FloatField()),
                ('nObs', models.IntegerField()),
                ('std', models.FloatField()),
                ('mean', models.FloatField()),
                ('ratio', models.FloatField()),
                ('activeRange', models.FloatField()),
                ('max_val', models.FloatField()),
                ('dist', models.TextField()),
            ],
        ),
    ]
