# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contourVals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nObs', models.IntegerField()),
                ('confidence_vals', models.TextField()),
                ('xi_vals', models.TextField()),
                ('paths', models.TextField()),
            ],
        ),
    ]
