# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlev', '0002_contourvals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contourvals',
            old_name='confidence_vals',
            new_name='conf',
        ),
        migrations.RenameField(
            model_name='contourvals',
            old_name='paths',
            new_name='ratio_vals',
        ),
        migrations.AddField(
            model_name='contourvals',
            name='res',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
