# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redlev', '0003_auto_20171120_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nObs', models.IntegerField()),
                ('xi', models.FloatField()),
                ('res', models.IntegerField()),
                ('ratio_vals', models.TextField()),
                ('prob_vals', models.TextField()),
            ],
        ),
    ]
