# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import recsys.models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('citation_only', models.BooleanField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('author', models.ManyToManyField(blank=True, null=True, to='recsys.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('pdf_url', models.URLField()),
                ('pdf', models.FileField(upload_to=recsys.models.pdf_path)),
                ('venue', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='recsys.Author')),
            ],
        ),
        migrations.AddField(
            model_name='citation',
            name='paper',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recsys.Paper'),
        ),
    ]
