# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0002_auto_20171219_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
