# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0003_citation_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='author',
            field=models.ManyToManyField(blank=True, to='recsys.Author'),
        ),
    ]
