# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0005_auto_20180104_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='paper',
            new_name='record',
        ),
        migrations.AlterField(
            model_name='paper',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
