# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0006_auto_20180105_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='citations',
            field=models.ManyToManyField(to='recsys.Citation'),
        ),
    ]
