# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0008_auto_20180105_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='cid',
            field=models.CharField(db_index=True, default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
