# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import recsys.models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0010_auto_20180105_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf',
            field=models.FileField(blank=True, upload_to=recsys.models.pdf_path),
        ),
        migrations.AlterField(
            model_name='paper',
            name='pdf_url',
            field=models.URLField(blank=True),
        ),
    ]
