# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0012_auto_20180117_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='the_citations',
            new_name='citations',
        ),
    ]
