# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0013_auto_20180117_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citationcontext',
            old_name='from_paper_id',
            new_name='from_paper',
        ),
        migrations.RenameField(
            model_name='citationcontext',
            old_name='to_paper_id',
            new_name='to_paper',
        ),
    ]
