# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0014_auto_20180117_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='cid',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
