# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0015_auto_20180118_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(blank=True, to='recsys.Author'),
        ),
    ]
