# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0019_auto_20180302_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='citation_only',
            field=models.BooleanField(default=False),
        ),
    ]
