# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-08 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0020_auto_20180608_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
