# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0021_paper_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='added_to_db',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
