# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0022_paper_added_to_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='next_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='added_to_db',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
