# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0024_remove_paper_pdf_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocitation',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='cocitation',
            name='with_paper',
        ),
        migrations.AddField(
            model_name='cocitation',
            name='co_from_paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='co_from_paper', to='recsys.Paper'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cocitation',
            name='co_to_paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='co_to_paper', to='recsys.Paper'),
            preserve_default=False,
        ),
    ]
